version: '2'

services:
  web:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      - PORT=8080
      - SECURE_PORT=8443
      - SERVICE_NAME=web
      - ERLANG_COOKIE=asd&%rewss
    volumes:
      - .:/home/elixir/app
      - ../app:/home/elixir/tokumei
    command: sh start.sh
