version: '3.1'

services:
  www:
    build:
      context: "./www"
      dockerfile: "Dockerfile"
    environment:
      - PORT=8080
      - SECURE_PORT=8443
      - ERLANG_COOKIE=asd&%rewss
    volumes:
      - ./www:/home/elixir/app
    ports:
      - "8443:8443"
      - "4001:4001"
    secrets:
      - certfile
      - keyfile
secrets:
  certfile:
    file: ./secrets/certificate.pem
  keyfile:
    file: ./secrets/certificate_key.pem
