FORMAT: 1A

# My new Project

Get started on your new application here

# Index [/]

## Home Page [GET]

Main page for everything.

## Publish A Message [POST]

Send a new message to the chat room.

# Updates [/updates]

## Subscribe to updates [GET]

Endpoint to fetch all the messages
