FORMAT: 1A

# Water Cooler

This site is a simple chat application.
It is a demonstration project for Elixir and [Tokumei]()

# Index [/]

## Home Page [GET]

Main page for chatroom.

## Publish message [POST]

Send a message to everyone in the chatroom.

# Updates [/updates]

## Subscribe to Messages [GET]

Receive messages to the chatroom as they are published.
